spring:
  application:
    name: sanji-jiksong

  h2:
    console:
      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
      path: /h2-console  # H2 Console의 Path

  datasource:
    url: ${DB_URL:jdbc:h2:mem:test}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}

  sql:
    init:
      mode: ${SQL_INIT_MODE:never}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: ${JPA_DDI:false}


  config:
    import: optional:file:.env[.properties]